import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import type { Level } from '@/types'

interface Props { level: Level; onComplete: (passed: boolean, hintsUsed: number) => void }
type Difficulty = 'easy'|'medium'|'hard'|'expert'
type Kind = 'parser'|'match'|'action'|'control'|'metadata'
interface Block { id:string; code:string; label:string; kind:Kind }
interface CodeLine { text?:string; slot?:string; indent?:number }
interface Challenge { title:string; difficulty:Difficulty; objective:string; lines:CodeLine[]; expected:Record<string,string>; palette:string[]; packet:string[]; result:string; explanation:string; hints:string[] }

const BLOCKS:Block[]=[
  {id:'parse-ethernet',code:'packet.extract(hdr.ethernet);',label:'Extract Ethernet header',kind:'parser'},
  {id:'parse-ipv4',code:'packet.extract(hdr.ipv4);',label:'Extract IPv4 header',kind:'parser'},
  {id:'parse-tcp',code:'packet.extract(hdr.tcp);',label:'Extract TCP header',kind:'parser'},
  {id:'transition-ipv4',code:'transition select(hdr.ethernet.etherType) { 0x0800: parse_ipv4; }',label:'IPv4 EtherType transition',kind:'parser'},
  {id:'transition-tcp',code:'transition select(hdr.ipv4.protocol) { 6: parse_tcp; }',label:'TCP protocol transition',kind:'parser'},
  {id:'accept',code:'transition accept;',label:'Accept packet',kind:'parser'},
  {id:'key-lpm',code:'hdr.ipv4.dstAddr : lpm;',label:'IPv4 destination LPM key',kind:'match'},
  {id:'key-ssh',code:'hdr.tcp.dstPort : exact;',label:'TCP destination exact key',kind:'match'},
  {id:'key-vlan',code:'hdr.vlan.vid : exact;',label:'VLAN exact key',kind:'match'},
  {id:'default-drop',code:'default_action = drop();',label:'Default drop action',kind:'control'},
  {id:'apply-lpm',code:'ipv4_lpm.apply();',label:'Apply IPv4 LPM table',kind:'control'},
  {id:'apply-firewall',code:'firewall.apply();',label:'Apply firewall table',kind:'control'},
  {id:'apply-mac',code:'mac_rewrite.apply();',label:'Apply MAC rewrite table',kind:'control'},
  {id:'set-egress',code:'standard_metadata.egress_spec = port;',label:'Set egress port',kind:'action'},
  {id:'ttl-dec',code:'hdr.ipv4.ttl = hdr.ipv4.ttl - 1;',label:'Decrement IPv4 TTL',kind:'action'},
  {id:'rewrite-dst',code:'hdr.ethernet.dstAddr = next_hop_mac;',label:'Rewrite destination MAC',kind:'action'},
  {id:'drop',code:'mark_to_drop(standard_metadata);',label:'Drop packet',kind:'action'},
  {id:'set-vlan-100',code:'hdr.vlan.vid = 100;',label:'Assign VLAN 100',kind:'action'},
  {id:'int-queue',code:'hdr.int.queue_depth = standard_metadata.deq_qdepth;',label:'Write INT queue depth',kind:'metadata'},
  {id:'int-time',code:'hdr.int.timestamp = standard_metadata.ingress_global_timestamp;',label:'Write INT timestamp',kind:'metadata'},
  {id:'emit-ethernet',code:'packet.emit(hdr.ethernet);',label:'Emit Ethernet header',kind:'parser'},
  {id:'emit-ipv4',code:'packet.emit(hdr.ipv4);',label:'Emit IPv4 header',kind:'parser'},
  {id:'emit-tcp',code:'packet.emit(hdr.tcp);',label:'Emit TCP header',kind:'parser'},
]

const CHALLENGES:Challenge[]=[
  {title:'Complete the Ethernet Parser',difficulty:'easy',objective:'Extract Ethernet before choosing the next protocol.',lines:[{text:'state parse_ethernet {'},{slot:'a',indent:1},{text:'transition select(hdr.ethernet.etherType) {',indent:1},{text:'0x0800: parse_ipv4;',indent:2},{text:'}',indent:1},{text:'}'}],expected:{a:'parse-ethernet'},palette:['parse-ipv4','parse-ethernet','parse-tcp','accept'],packet:['EtherType 0x0800','Payload IPv4','Length 128 B'],result:'Ethernet and IPv4 headers become valid.',explanation:'The outer Ethernet header must be extracted before its EtherType can select IPv4.',hints:['This is the first header on an Ethernet link.','The state name tells you which header to extract.','Use packet.extract(hdr.ethernet).']},
  {title:'Route EtherType to IPv4',difficulty:'easy',objective:'Complete the transition from Ethernet to the IPv4 parser.',lines:[{text:'state parse_ethernet {'},{text:'packet.extract(hdr.ethernet);',indent:1},{slot:'a',indent:1},{text:'}'}],expected:{a:'transition-ipv4'},palette:['transition-tcp','accept','transition-ipv4','parse-ipv4'],packet:['EtherType 0x0800','Protocol 6 (TCP)','Destination 10.0.0.8'],result:'Parser enters parse_ipv4.',explanation:'EtherType 0x0800 identifies IPv4 and transitions to parse_ipv4.',hints:['Inspect Ethernet EtherType, not the IP protocol field.','IPv4 EtherType is 0x0800.','Choose the EtherType transition block.']},
  {title:'Parse TCP After IPv4',difficulty:'easy',objective:'Extract TCP when the IPv4 protocol field is 6.',lines:[{text:'state parse_ipv4 {'},{text:'packet.extract(hdr.ipv4);',indent:1},{slot:'a',indent:1},{text:'}'},{text:'state parse_tcp {'},{slot:'b',indent:1},{text:'transition accept;',indent:1},{text:'}'}],expected:{a:'transition-tcp',b:'parse-tcp'},palette:['parse-tcp','transition-ipv4','transition-tcp','parse-ipv4','accept'],packet:['EtherType IPv4','IP protocol 6','TCP dst 443'],result:'IPv4 and TCP headers become valid.',explanation:'IPv4 protocol 6 selects the TCP parser, which then extracts hdr.tcp.',hints:['Protocol 6 means TCP.','One slot chooses the state; the other extracts its header.','Use transition-tcp followed by parse-tcp.']},
  {title:'Define the LPM Match Key',difficulty:'medium',objective:'Complete an IPv4 longest-prefix-match table.',lines:[{text:'table ipv4_lpm {'},{text:'key = {',indent:1},{slot:'a',indent:2},{text:'}',indent:1},{text:'actions = { ipv4_forward; drop; }',indent:1},{text:'}'}],expected:{a:'key-lpm'},palette:['key-ssh','key-vlan','key-lpm','default-drop'],packet:['IPv4 dst 10.4.2.9','Candidate 10.4.0.0/16','Candidate 10.4.2.0/24'],result:'The /24 entry wins and selects port 3.',explanation:'IPv4 routing uses the destination address with longest-prefix-match semantics.',hints:['Routing looks at where the packet is going.','The match type must choose the longest prefix.','Use hdr.ipv4.dstAddr : lpm.']},
  {title:'Protect the Table Miss',difficulty:'medium',objective:'Drop packets that match no IPv4 forwarding entry.',lines:[{text:'table ipv4_lpm {'},{text:'key = { hdr.ipv4.dstAddr : lpm; }',indent:1},{text:'actions = { ipv4_forward; drop; }',indent:1},{slot:'a',indent:1},{text:'}'}],expected:{a:'default-drop'},palette:['apply-lpm','set-egress','default-drop','accept'],packet:['IPv4 dst 203.0.113.7','No matching prefix','Ingress port 1'],result:'The unmatched packet is dropped.',explanation:'A safe default action prevents unmatched traffic from being forwarded accidentally.',hints:['This code runs only when no entry matches.','Choose a default behavior, not a table apply call.','Use default_action = drop().']},
  {title:'Finish the IPv4 Forward Action',difficulty:'medium',objective:'Set the egress port and decrement TTL before forwarding.',lines:[{text:'action ipv4_forward(bit<9> port) {'},{slot:'a',indent:1},{text:'hdr.ethernet.dstAddr = next_hop_mac;',indent:1},{slot:'b',indent:1},{text:'}'}],expected:{a:'set-egress',b:'ttl-dec'},palette:['ttl-dec','drop','set-egress','rewrite-dst','set-vlan-100'],packet:['IPv4 TTL 64','Selected port 4','Next hop MAC known'],result:'Packet exits port 4 with TTL 63.',explanation:'A routed packet needs an egress decision and TTL decrement.',hints:['The first missing line selects an output port.','Routers reduce TTL by exactly one.','Place set-egress first and ttl-dec last.']},
  {title:'Build the SSH Firewall Key',difficulty:'hard',objective:'Match the service field needed to block SSH.',lines:[{text:'table firewall {'},{text:'key = {',indent:1},{slot:'a',indent:2},{text:'}',indent:1},{text:'actions = { allow; drop; }',indent:1},{slot:'b',indent:1},{text:'}'}],expected:{a:'key-ssh',b:'default-drop'},palette:['default-drop','key-lpm','key-ssh','key-vlan','apply-firewall'],packet:['TCP dst port 22','Source 198.51.100.4','Destination server'],result:'SSH packet matches and is dropped.',explanation:'The firewall performs an exact match on TCP destination port and defaults to drop.',hints:['SSH is identified at the transport layer.','The table needs both a key and safe default.','Use key-ssh, then default-drop.']},
  {title:'Order the Ingress Tables',difficulty:'hard',objective:'Apply policy before routing and MAC rewrite after routing.',lines:[{text:'apply {'},{slot:'a',indent:1},{slot:'b',indent:1},{slot:'c',indent:1},{text:'}'}],expected:{a:'apply-firewall',b:'apply-lpm',c:'apply-mac'},palette:['apply-mac','apply-firewall','apply-lpm','default-drop','set-egress'],packet:['Tenant packet','Firewall allow','IPv4 route port 2','Next-hop MAC'],result:'Policy passes, route resolves, MAC is rewritten.',explanation:'Firewall policy runs first, LPM chooses the route, and MAC rewrite prepares the next hop.',hints:['Enforce security before forwarding.','MAC rewrite depends on the route decision.','Order: firewall, LPM, MAC rewrite.']},
  {title:'Tag the Tenant VLAN',difficulty:'hard',objective:'Assign VLAN 100 before applying IPv4 forwarding.',lines:[{text:'action classify_tenant() {'},{slot:'a',indent:1},{text:'}'},{text:'apply {'},{text:'classify_tenant();',indent:1},{slot:'b',indent:1},{text:'}'}],expected:{a:'set-vlan-100',b:'apply-lpm'},palette:['apply-lpm','key-vlan','set-vlan-100','drop','apply-firewall'],packet:['Tenant Sales','Untagged frame','Destination 10.10.0.5'],result:'Frame carries VLAN 100 and follows the IPv4 route.',explanation:'Classification assigns the VLAN before the routing table processes the packet.',hints:['The action changes a header field.','Routing happens after classification.','Use set-vlan-100 then apply-lpm.']},
  {title:'Write INT Telemetry',difficulty:'expert',objective:'Add queue depth and timestamp metadata during egress.',lines:[{text:'control Egress(...) {'},{text:'apply {',indent:1},{slot:'a',indent:2},{slot:'b',indent:2},{text:'}',indent:1},{text:'}'}],expected:{a:'int-queue',b:'int-time'},palette:['int-time','ttl-dec','int-queue','set-egress','emit-ipv4'],packet:['Queue depth 18','Timestamp 90421','Switch ID 7'],result:'INT header reports queue depth 18 and timestamp 90421.',explanation:'INT writes live switch metadata into packet headers before deparsing.',hints:['Both missing lines write telemetry metadata.','Queue depth comes before timestamp in this template.','Use int-queue then int-time.']},
  {title:'Reassemble the Packet',difficulty:'expert',objective:'Emit Ethernet, IPv4, and TCP headers in wire order.',lines:[{text:'control Deparser(packet_out packet, Headers hdr) {'},{text:'apply {',indent:1},{slot:'a',indent:2},{slot:'b',indent:2},{slot:'c',indent:2},{text:'}',indent:1},{text:'}'}],expected:{a:'emit-ethernet',b:'emit-ipv4',c:'emit-tcp'},palette:['emit-tcp','parse-ipv4','emit-ethernet','emit-ipv4','parse-tcp'],packet:['Ethernet valid','IPv4 valid','TCP valid'],result:'Output packet is Ethernet → IPv4 → TCP → payload.',explanation:'The deparser emits valid headers from outermost to innermost.',hints:['Start with the link-layer header.','TCP is inside IPv4.','Order: Ethernet, IPv4, TCP.']},
  {title:'Complete the Full P4 Pipeline',difficulty:'expert',objective:'Fill the parser, ingress, egress telemetry, and deparser gaps.',lines:[{text:'// Parser'},{slot:'a'},{text:'// Ingress'},{slot:'b'},{text:'// Egress'},{slot:'c'},{text:'// Deparser'},{slot:'d'}],expected:{a:'transition-ipv4',b:'apply-lpm',c:'int-queue',d:'emit-ethernet'},palette:['emit-ethernet','apply-firewall','int-queue','transition-ipv4','emit-tcp','apply-lpm','ttl-dec'],packet:['EtherType IPv4','IPv4 dst 10.0.0.8','Queue depth 12','TCP dst 443'],result:'Packet parses, routes, gains telemetry, and is emitted.',explanation:'A complete P4 program connects parser transitions, ingress tables, egress metadata, and ordered deparsing.',hints:['Each slot belongs to a different named stage.','Choose one parser, table, telemetry, and emit block.','Use transition-ipv4, apply-lpm, int-queue, emit-ethernet.']},
]

const DIFFICULTIES:Difficulty[]=['easy','medium','hard','expert']
const STYLE:Record<Kind,string>={parser:'border-link-packet/60 bg-link-packet/15 text-link-packet',match:'border-module-b/60 bg-module-b/15 text-module-b',action:'border-link-up/60 bg-link-up/15 text-link-up',control:'border-module-c/60 bg-module-c/15 text-module-c',metadata:'border-link-congested/60 bg-link-congested/15 text-link-congested'}

export function CodeBuilderIDE({level,onComplete}:Props){
  const navigate=useNavigate();const [difficulty,setDifficulty]=useState<Difficulty>('easy');const [index,setIndex]=useState(0);const [slots,setSlots]=useState<Record<string,string>>({});const [dragged,setDragged]=useState<string|null>(null);const [selected,setSelected]=useState<string|null>(null);const [hintCount,setHintCount]=useState(0);const [xp,setXp]=useState(0);const [status,setStatus]=useState<'idle'|'partial'|'wrong'|'correct'>('idle');const [complete,setComplete]=useState(false)
  const pool=useMemo(()=>CHALLENGES.filter((item)=>item.difficulty===difficulty),[difficulty]);const challenge=pool[index%pool.length];const diffIndex=DIFFICULTIES.indexOf(difficulty);const filled=Object.keys(slots).length;const total=Object.keys(challenge.expected).length
  function reset(next=index){setIndex(next);setSlots({});setSelected(null);setStatus('idle');setComplete(false);setHintCount(0)}
  function changeDifficulty(next:Difficulty){setDifficulty(next);reset(0)}
  function place(slot:string,id:string){setSlots((current)=>({...current,[slot]:id}));setSelected(null);setStatus('idle')}
  function choose(id:string){setSelected(id);const empty=Object.keys(challenge.expected).find((slot)=>!slots[slot]);if(empty)place(empty,id)}
  function run(){const entries=Object.entries(challenge.expected);const correct=entries.filter(([slot,id])=>slots[slot]===id).length;if(correct===entries.length){setStatus('correct');setXp((value)=>value+50);setComplete(true)}else setStatus(correct>0?'partial':'wrong')}
  const availableBlocks=challenge.palette.map((id)=>BLOCKS.find((block)=>block.id===id)!)
  return <div className="overflow-hidden rounded-xl border border-noc-border bg-[#0b1017] shadow-2xl shadow-black/30"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-noc-border bg-noc-surface px-4 py-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-link-packet/15 font-mono font-bold text-link-packet">&lt;/&gt;</div><div><p className="text-sm font-bold text-noc-bright">P4 CODE COMPLETION LAB</p><p className="text-[10px] text-noc-muted">{level.id} · Fill the missing code chunks</p></div></div><div className="text-center"><p className="text-sm font-semibold text-module-b">{challenge.title}</p><p className="text-[10px] text-noc-muted">Challenge {CHALLENGES.indexOf(challenge)+1} of {CHALLENGES.length}</p></div><div className="flex items-center gap-2"><span className="rounded bg-module-b/15 px-2 py-1 text-xs capitalize text-module-b">{difficulty}</span><span className="rounded bg-link-congested/10 px-2 py-1 font-mono text-xs text-link-congested">XP {xp}</span></div></header>
    <div className="grid min-h-[680px] lg:grid-cols-[245px_1fr_270px]"><aside className="border-r border-noc-border bg-noc-surface/70 p-3"><p className="text-xs font-bold uppercase tracking-widest text-noc-muted">Code Chunks</p><p className="mb-3 mt-1 text-[10px] text-noc-muted">Drag a chunk into a blank, or click to fill the next blank.</p><div className="flex flex-col gap-2">{availableBlocks.map((block)=><button key={block.id} draggable onDragStart={()=>setDragged(block.id)} onClick={()=>choose(block.id)} className={`rounded border px-2 py-2 text-left font-mono text-[10px] ${selected===block.id?'ring-2 ring-noc-bright ':''}${STYLE[block.kind]}`}><span className="mb-1 block font-sans text-[9px] opacity-70">{block.label}</span>{block.code}</button>)}</div><div className="mt-5 rounded-lg border border-noc-border bg-noc-bg/60 p-3"><p className="text-[10px] uppercase text-noc-muted">Completion</p><p className="mt-1 text-sm text-noc-text">{filled} / {total} blanks filled</p></div></aside>
      <main className="min-w-0 p-4"><div className="mb-3 rounded-lg border border-noc-border bg-noc-surface/60 p-3"><p className="text-[10px] uppercase tracking-widest text-noc-muted">Objective</p><p className="mt-1 text-sm text-noc-text">{challenge.objective}</p></div><div className="min-h-[540px] rounded-lg border border-noc-border bg-[#0d141e] p-3"><div className="mb-3 grid grid-cols-[36px_1fr] text-[10px] text-noc-muted"><span>LINE</span><span>PARTIALLY WRITTEN P4 PROGRAM</span></div>{challenge.lines.map((line,lineIndex)=>{const slotId=line.slot;const placedId=slotId?slots[slotId]:undefined;const block=placedId?BLOCKS.find((item)=>item.id===placedId):null;return <div key={lineIndex} className="grid grid-cols-[36px_1fr] items-center py-1"><span className="text-right font-mono text-[10px] text-noc-muted">{lineIndex+1}</span>{slotId?<button onDragOver={(event)=>event.preventDefault()} onDrop={()=>{if(dragged)place(slotId,dragged);setDragged(null)}} onClick={()=>{if(selected)place(slotId,selected)}} className={`ml-3 min-h-10 rounded border border-dashed px-3 py-2 text-left font-mono text-xs ${block?STYLE[block.kind]:'border-link-congested/60 bg-link-congested/5 text-link-congested'}`} style={{marginLeft:`${12+(line.indent??0)*22}px`}}>{block?block.code:`[ drop code for ${slotId} here ]`}</button>:<div className="ml-3 whitespace-pre-wrap font-mono text-xs text-noc-text" style={{marginLeft:`${12+(line.indent??0)*22}px`}}>{line.text}</div>}</div>})}</div></main>
      <aside className="border-l border-noc-border bg-noc-surface/60 p-3"><section className="rounded-lg border border-noc-border bg-noc-bg/60 p-3"><p className="text-xs font-bold text-noc-bright">Packet Test</p>{challenge.packet.map((line)=><div key={line} className="mt-2 border-b border-noc-border/50 pb-1 font-mono text-[10px] text-noc-muted">{line}</div>)}</section><section className="mt-3 rounded-lg border border-noc-border bg-noc-bg/60 p-3"><p className="text-xs font-bold text-noc-bright">Output / Feedback</p>{status==='idle'&&<p className="mt-3 text-xs text-noc-muted">Complete the blanks, then run the packet test.</p>}{status==='partial'&&<p className="mt-3 rounded border border-link-congested/40 bg-link-congested/10 p-3 text-xs text-link-congested">Partially correct. Some chunks are in the right slots; inspect the remaining stages.</p>}{status==='wrong'&&<p className="mt-3 rounded border border-link-down/40 bg-link-down/10 p-3 text-xs text-link-down">The selected chunks do not match this pipeline behavior.</p>}{status==='correct'&&<div className="mt-3 rounded border border-link-up/40 bg-link-up/10 p-3"><p className="text-xs font-bold text-link-up">✓ Packet test passed</p><p className="mt-1 text-[10px] text-noc-text">{challenge.result}</p></div>}</section>{hintCount>0&&<div className="mt-3 rounded border border-link-congested/40 bg-link-congested/10 p-3 text-xs text-noc-text">💡 {challenge.hints[Math.min(hintCount-1,2)]}</div>}<div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setHintCount((value)=>Math.min(3,value+1))} className="rounded border border-link-congested/50 px-3 py-2 text-xs text-link-congested">Hint {Math.min(3,hintCount+1)}/3</button><button onClick={run} className="rounded bg-link-up px-3 py-2 text-xs font-bold text-noc-bg">▶ Run</button></div><button onClick={()=>setSlots({})} className="mt-2 w-full rounded border border-noc-border px-3 py-2 text-xs text-noc-muted">Clear Blanks</button></aside></div>
    <footer className="flex flex-wrap items-center gap-2 border-t border-noc-border bg-noc-surface px-4 py-3"><span className="mr-2 text-[10px] uppercase tracking-widest text-noc-muted">Difficulty</span>{DIFFICULTIES.map((item)=><button key={item} onClick={()=>changeDifficulty(item)} className={`rounded border px-3 py-1.5 text-xs capitalize ${difficulty===item?'border-module-b bg-module-b/15 text-module-b':'border-noc-border text-noc-muted'}`}>{item}</button>)}</footer>
    {complete&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-xl border border-link-up/50 bg-noc-surface p-6 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-link-up text-2xl font-bold text-noc-bg">✓</div><h3 className="mt-3 text-xl font-bold text-noc-bright">Code completed!</h3><p className="mt-1 text-sm text-link-up">+50 XP · Packet test passed</p><p className="mx-auto mt-3 max-w-lg text-xs text-noc-muted">{challenge.explanation}</p><div className={`mt-6 grid gap-3 ${difficulty==='expert'?'sm:grid-cols-2':'sm:grid-cols-3'}`}><button onClick={()=>reset((index+1)%pool.length)} className="rounded border border-link-packet/50 bg-link-packet/10 px-4 py-3 text-sm font-semibold text-link-packet">Another Challenge</button>{difficulty!=='expert'&&<button onClick={()=>changeDifficulty(DIFFICULTIES[diffIndex+1])} className="rounded border border-link-congested/50 bg-link-congested/10 px-4 py-3 text-sm font-semibold text-link-congested">Try Harder Level</button>}<button onClick={()=>{onComplete(true,hintCount);navigate('/sandbox')}} className="rounded bg-link-up px-4 py-3 text-sm font-bold text-noc-bg">Back to Sandbox</button></div></div></div>}
  </div>
}
