import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import type { Level } from '@/types'

interface Props { level:Level; onComplete:(passed:boolean,hintsUsed:number)=>void }
type SectionId='fundamentals'|'tahoe'|'reno'|'vegas'|'bbr'|'cubic'
type Kind='event'|'condition'|'action'|'formula'
interface Block { id:string; code:string; label:string; kind:Kind }
interface Variant { title:string; missing:number[]; distractors:string[]; packet:string[]; hint:string }
interface Section { title:string; goal:string; program:string[]; variants:Variant[]; explanation:string }

const BLOCKS:Block[]=[
  {id:'on-ack',code:'on ACK_received:',label:'ACK event',kind:'event'},{id:'on-timeout',code:'on timeout:',label:'Timeout event',kind:'event'},{id:'on-dup3',code:'on duplicate_ACK_count == 3:',label:'Three duplicate ACKs',kind:'event'},{id:'on-new-ack',code:'on new_ACK:',label:'New ACK event',kind:'event'},{id:'on-rtt',code:'on new_RTT_sample:',label:'New RTT sample',kind:'event'},{id:'on-loss',code:'on packet_loss:',label:'Loss event',kind:'event'},
  {id:'if-slow',code:'if cwnd < ssthresh:',label:'Slow Start condition',kind:'condition'},{id:'else',code:'else:',label:'Else branch',kind:'condition'},{id:'if-alpha',code:'if Diff < alpha:',label:'Vegas below alpha',kind:'condition'},{id:'else-beta',code:'else if Diff > beta:',label:'Vegas above beta',kind:'condition'},
  {id:'inc-mss',code:'cwnd = cwnd + 1 MSS',label:'Increase by one MSS',kind:'action'},{id:'aimd-inc',code:'cwnd = cwnd + MSS*MSS/cwnd',label:'AIMD additive increase',kind:'action'},{id:'halve',code:'ssthresh = max(cwnd / 2, 2 MSS)',label:'Halve threshold',kind:'action'},{id:'cwnd-one',code:'cwnd = 1 MSS',label:'Reset cwnd',kind:'action'},{id:'slow-start',code:'phase = SLOW_START',label:'Enter Slow Start',kind:'action'},{id:'avoidance',code:'phase = CONGESTION_AVOIDANCE',label:'Enter Congestion Avoidance',kind:'action'},{id:'fast-retransmit',code:'retransmit_missing_segment()',label:'Fast Retransmit',kind:'action'},{id:'fast-recovery',code:'phase = FAST_RECOVERY',label:'Enter Fast Recovery',kind:'action'},{id:'cwnd-thresh3',code:'cwnd = ssthresh + 3 MSS',label:'Inflate recovery window',kind:'action'},{id:'cwnd-thresh',code:'cwnd = ssthresh',label:'Deflate recovery window',kind:'action'},{id:'dec-mss',code:'cwnd = cwnd - 1 MSS',label:'Decrease by one MSS',kind:'action'},{id:'keep',code:'cwnd = cwnd',label:'Keep cwnd',kind:'action'},
  {id:'expected',code:'Expected = cwnd / BaseRTT',label:'Vegas expected rate',kind:'formula'},{id:'actual',code:'Actual = cwnd / CurrentRTT',label:'Vegas actual rate',kind:'formula'},{id:'diff',code:'Diff = Expected - Actual',label:'Vegas difference',kind:'formula'},{id:'measure-rtt',code:'RTprop = min(RTprop, RTT_sample)',label:'Measure minimum RTT',kind:'formula'},{id:'estimate-bw',code:'BtlBw = max(delivered / interval)',label:'Estimate bottleneck bandwidth',kind:'formula'},{id:'bdp',code:'BDP = BtlBw * RTprop',label:'Compute BDP',kind:'formula'},{id:'set-bdp',code:'cwnd = gain * BDP',label:'Set BBR cwnd',kind:'action'},{id:'pace-bw',code:'pacing_rate = gain * BtlBw',label:'Set pacing rate',kind:'action'},
  {id:'wmax',code:'W_max = cwnd',label:'Save window peak',kind:'action'},{id:'cubic-reduce',code:'cwnd = beta * W_max',label:'CUBIC loss reduction',kind:'formula'},{id:'epoch',code:'epoch_start = now',label:'Start CUBIC epoch',kind:'action'},{id:'time-loss',code:'t = now - epoch_start',label:'Time since loss',kind:'formula'},{id:'cubic-k',code:'K = cbrt(W_max * (1-beta) / C)',label:'CUBIC K formula',kind:'formula'},{id:'cubic-window',code:'target = C*(t-K)^3 + W_max',label:'CUBIC growth formula',kind:'formula'},{id:'set-target',code:'cwnd = max(cwnd, target)',label:'Apply CUBIC target',kind:'action'},
]

const SECTIONS:Record<SectionId,Section>={
  fundamentals:{title:'TCP Fundamentals',goal:'Complete Slow Start, AIMD, and timeout behavior.',program:['on-ack','if-slow','inc-mss','else','aimd-inc','on-timeout','halve','cwnd-one','slow-start'],explanation:'ACKs grow cwnd exponentially below ssthresh and additively above it; timeout halves ssthresh and restarts at one MSS.',variants:[
    {title:'Slow Start Condition',missing:[1],distractors:['if-alpha','on-dup3'],packet:['cwnd 10 MSS','ssthresh 16 MSS','ACK received'],hint:'Slow Start continues while cwnd is below ssthresh.'},
    {title:'Slow Start Growth',missing:[2],distractors:['aimd-inc','dec-mss'],packet:['cwnd 10 MSS','ssthresh 16 MSS','ACK received'],hint:'Each ACK adds one MSS during Slow Start.'},
    {title:'Congestion Avoidance Formula',missing:[4],distractors:['inc-mss','cwnd-one'],packet:['cwnd 18 MSS','ssthresh 16 MSS','ACK received'],hint:'AIMD adds roughly one MSS per RTT, spread across ACKs.'},
    {title:'Timeout Threshold',missing:[6],distractors:['cubic-reduce','cwnd-thresh3'],packet:['cwnd 24 MSS','timeout','MSS 1460 B'],hint:'After timeout, ssthresh becomes half of the old cwnd.'},
    {title:'Timeout Recovery',missing:[7,8],distractors:['fast-recovery','avoidance','cwnd-thresh'],packet:['cwnd 24 MSS','ssthresh becomes 12','timeout'],hint:'A timeout is severe: reset cwnd and return to Slow Start.'},
  ]},
  tahoe:{title:'TCP Tahoe',goal:'Complete Tahoe loss recovery without Fast Recovery.',program:['on-dup3','halve','fast-retransmit','cwnd-one','slow-start','on-timeout','halve','cwnd-one','slow-start'],explanation:'Tahoe fast-retransmits after three duplicate ACKs but resets cwnd to one MSS and enters Slow Start for every loss signal.',variants:[
    {title:'Tahoe Duplicate-ACK Event',missing:[0],distractors:['on-timeout','on-ack'],packet:['DupACK 3','cwnd 20 MSS','one segment missing'],hint:'Fast Retransmit begins after three duplicate ACKs.'},
    {title:'Tahoe Fast Retransmit',missing:[2],distractors:['fast-recovery','keep'],packet:['DupACK 3','receiver repeats ACK 1001'],hint:'Tahoe retransmits immediately, but does not enter Fast Recovery.'},
    {title:'Tahoe Window Reset',missing:[3],distractors:['cwnd-thresh3','cwnd-thresh'],packet:['cwnd 20 MSS','ssthresh 10 MSS','DupACK 3'],hint:'Tahoe always collapses cwnd to one after loss.'},
    {title:'Tahoe Timeout Order',missing:[5,6],distractors:['on-new-ack','cubic-reduce','fast-recovery'],packet:['retransmission timer expired','cwnd 32 MSS'],hint:'A timeout event first updates the threshold.'},
    {title:'Tahoe Complete Recovery',missing:[6,7,8],distractors:['avoidance','cwnd-thresh3','fast-recovery'],packet:['timeout','cwnd 32 MSS','ssthresh 16 MSS'],hint:'Halve threshold, reset cwnd, enter Slow Start.'},
  ]},
  reno:{title:'TCP Reno & NewReno',goal:'Complete Fast Retransmit, Fast Recovery, and timeout branches.',program:['on-dup3','halve','cwnd-thresh3','fast-retransmit','fast-recovery','on-new-ack','cwnd-thresh','avoidance','on-timeout','halve','cwnd-one','slow-start'],explanation:'Reno treats duplicate ACK loss mildly with Fast Recovery, but treats timeout severely by restarting Slow Start.',variants:[
    {title:'Reno Recovery Window',missing:[2],distractors:['cwnd-one','cwnd-thresh','inc-mss'],packet:['DupACK 3','cwnd 24 MSS','ssthresh 12 MSS'],hint:'Reno inflates cwnd by three MSS for packets still in flight.'},
    {title:'Enter Fast Recovery',missing:[3,4],distractors:['slow-start','dec-mss','keep'],packet:['DupACK 3','lost segment detected'],hint:'Retransmit first, then enter Fast Recovery.'},
    {title:'Exit Fast Recovery',missing:[5,6,7],distractors:['on-timeout','cwnd-one','slow-start'],packet:['new cumulative ACK','recovery complete'],hint:'A new ACK deflates cwnd and returns to Congestion Avoidance.'},
    {title:'Reno Timeout Difference',missing:[8,10,11],distractors:['on-dup3','cwnd-thresh3','fast-recovery'],packet:['timeout','cwnd 24 MSS'],hint:'Unlike DupACK recovery, timeout resets cwnd to one.'},
    {title:'Reno Threshold Formula',missing:[1,9],distractors:['cubic-reduce','aimd-inc'],packet:['loss signals','cwnd before loss 30 MSS'],hint:'Both Reno loss branches halve ssthresh.'},
  ]},
  vegas:{title:'TCP Vegas',goal:'Complete delay-based congestion detection and response.',program:['on-rtt','expected','actual','diff','if-alpha','inc-mss','else-beta','dec-mss','else','keep'],explanation:'Vegas compares expected and actual throughput to infer queued data before loss occurs.',variants:[
    {title:'Expected Throughput',missing:[1],distractors:['actual','bdp'],packet:['cwnd 20 MSS','BaseRTT 50 ms','CurrentRTT 80 ms'],hint:'Expected rate uses the minimum observed RTT.'},
    {title:'Actual Throughput',missing:[2],distractors:['expected','estimate-bw'],packet:['cwnd 20 MSS','CurrentRTT 80 ms'],hint:'Actual rate uses the current measured RTT.'},
    {title:'Vegas Queue Difference',missing:[3],distractors:['bdp','cubic-window'],packet:['Expected 400 MSS/s','Actual 250 MSS/s'],hint:'Subtract actual throughput from expected throughput.'},
    {title:'Vegas Increase Branch',missing:[4,5],distractors:['else-beta','dec-mss','keep'],packet:['Diff 1.5','alpha 2','beta 4'],hint:'Below alpha means the path is underutilized.'},
    {title:'Vegas Three-Way Decision',missing:[6,7,8,9],distractors:['if-slow','cwnd-one','fast-recovery'],packet:['Diff between alpha and beta','no loss'],hint:'Above beta decrease; between thresholds keep cwnd.'},
  ]},
  bbr:{title:'BBR',goal:'Complete bandwidth and RTT model-based control.',program:['on-rtt','measure-rtt','estimate-bw','bdp','set-bdp','pace-bw'],explanation:'BBR estimates bottleneck bandwidth and propagation RTT, then targets their product instead of waiting for packet loss.',variants:[
    {title:'Measure Propagation RTT',missing:[1],distractors:['actual','diff'],packet:['RTT sample 45 ms','previous RTprop 50 ms'],hint:'RTprop is the minimum observed RTT.'},
    {title:'Estimate Bottleneck Bandwidth',missing:[2],distractors:['expected','aimd-inc'],packet:['delivered 12 MB','interval 100 ms'],hint:'Delivery rate estimates available bottleneck bandwidth.'},
    {title:'Compute Bandwidth-Delay Product',missing:[3],distractors:['diff','cubic-k'],packet:['BtlBw 1 Gbps','RTprop 40 ms'],hint:'BDP is bandwidth multiplied by RTT.'},
    {title:'Set BBR Congestion Window',missing:[4],distractors:['cwnd-one','cubic-reduce'],packet:['BDP 5000 packets','cwnd gain 2'],hint:'BBR sets cwnd from a gain times BDP.'},
    {title:'Complete the BBR Model',missing:[1,2,3,5],distractors:['halve','fast-recovery','cubic-window'],packet:['new RTT and delivery sample','ProbeBW phase'],hint:'Measure RTT, estimate bandwidth, compute BDP, then pace.'},
  ]},
  cubic:{title:'TCP CUBIC',goal:'Complete time-based cubic growth and loss response.',program:['on-loss','wmax','cubic-reduce','epoch','on-ack','time-loss','cubic-k','cubic-window','set-target'],explanation:'CUBIC reduces on loss, records W_max, then grows using a cubic function of time around the previous peak.',variants:[
    {title:'Remember the Previous Peak',missing:[1],distractors:['set-target','keep'],packet:['loss at cwnd 120 MSS','beta 0.7'],hint:'CUBIC saves the window immediately before reduction.'},
    {title:'CUBIC Loss Reduction',missing:[2],distractors:['halve','cwnd-one'],packet:['W_max 120 MSS','beta 0.7'],hint:'CUBIC multiplies W_max by beta after loss.'},
    {title:'Start a New CUBIC Epoch',missing:[3],distractors:['fast-recovery','slow-start'],packet:['loss recovery begins','clock 42 s'],hint:'CUBIC growth is based on time since the epoch began.'},
    {title:'Calculate K',missing:[5,6],distractors:['bdp','diff','expected'],packet:['W_max 120','beta 0.7','C 0.4'],hint:'Find elapsed time, then the cube-root offset K.'},
    {title:'Apply the Cubic Curve',missing:[7,8],distractors:['aimd-inc','set-bdp','halve'],packet:['t 8 s','K 4.5','W_max 120'],hint:'Compute C(t-K)^3 + W_max, then apply the target.'},
  ]},
}

const ORDER:SectionId[]=['fundamentals','tahoe','reno','vegas','bbr','cubic']
const STYLE:Record<Kind,string>={event:'border-module-b/60 bg-module-b/15 text-module-b',condition:'border-link-packet/60 bg-link-packet/15 text-link-packet',action:'border-link-up/60 bg-link-up/15 text-link-up',formula:'border-link-congested/60 bg-link-congested/15 text-link-congested'}

export function CongestionCodeLab({level,onComplete}:Props){
  const navigate=useNavigate();const sectionId=level.setup.codeSection as SectionId;const section=SECTIONS[sectionId];const sectionIndex=ORDER.indexOf(sectionId);const [questionIndex,setQuestionIndex]=useState(0);const [slots,setSlots]=useState<Record<string,string>>({});const [dragged,setDragged]=useState<string|null>(null);const [hintCount,setHintCount]=useState(0);const [attempts,setAttempts]=useState(0);const [status,setStatus]=useState<'idle'|'wrong'|'partial'|'correct'>('idle');const [complete,setComplete]=useState(false);const challenge=section.variants[questionIndex%section.variants.length]
  const slotByLine=new Map(challenge.missing.map((lineIndex,slotIndex)=>[lineIndex,`slot-${slotIndex}`]));const expected=Object.fromEntries(challenge.missing.map((lineIndex,slotIndex)=>[`slot-${slotIndex}`,section.program[lineIndex]]));const paletteIds=useMemo(()=>Array.from(new Set([...Object.values(expected),...challenge.distractors])),[challenge,section]);const palette=paletteIds.map((id)=>BLOCKS.find((block)=>block.id===id)!)
  function reset(next=questionIndex){setQuestionIndex(next);setSlots({});setStatus('idle');setComplete(false);setHintCount(0);setAttempts(0)}
  function place(slot:string,id:string){setSlots((current)=>({...current,[slot]:id}));setStatus('idle')}
  function choose(id:string){const empty=Object.keys(expected).find((slot)=>!slots[slot]);if(empty)place(empty,id)}
  function run(){const entries=Object.entries(expected);const correct=entries.filter(([slot,id])=>slots[slot]===id).length;if(correct===entries.length){setStatus('correct');setComplete(true)}else{setAttempts((n)=>n+1);setStatus(correct>0?'partial':'wrong')}}
  function nextSection(){onComplete(true,hintCount);const next=ORDER[sectionIndex+1];navigate(next?`/level/A-L${String(sectionIndex+2).padStart(2,'0')}`:'/sandbox')}
  return <div className="overflow-hidden rounded-xl border border-noc-border bg-[#0a111a]"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-noc-border bg-noc-surface px-4 py-3"><div><p className="text-sm font-bold text-noc-bright">TCP CONGESTION CONTROL LAB</p><p className="text-[10px] text-noc-muted">Practice · Complete · Simulate</p></div><div className="text-center"><p className="text-sm font-semibold text-module-b">{section.title}</p><p className="text-[10px] text-noc-muted">Question {questionIndex+1} of {section.variants.length} · {challenge.title}</p></div><span className="rounded bg-link-packet/15 px-2 py-1 text-xs text-link-packet">Section {sectionIndex+1}/{ORDER.length}</span></header>
    <div className="grid min-h-[700px] lg:grid-cols-[235px_1fr_330px]"><aside className="border-r border-noc-border bg-noc-surface/70 p-3"><p className="text-xs font-bold uppercase tracking-widest text-noc-muted">Missing Code Blocks</p><p className="mb-3 mt-1 text-[10px] text-noc-muted">Drag into a blank, or click to fill the next blank.</p><div className="flex flex-col gap-2">{palette.map((block)=><button key={block.id} draggable onDragStart={()=>setDragged(block.id)} onClick={()=>choose(block.id)} className={`rounded border px-2 py-2 text-left font-mono text-[10px] ${STYLE[block.kind]}`}><span className="mb-1 block font-sans text-[9px] opacity-70">{block.label}</span>{block.code}</button>)}</div><div className="mt-5 rounded border border-noc-border bg-noc-bg/60 p-3"><p className="text-[10px] uppercase text-noc-muted">Algorithm goal</p><p className="mt-1 text-xs text-noc-text">{section.goal}</p></div></aside>
      <main className="p-4"><div className="mb-3 rounded border border-noc-border bg-noc-surface/60 p-3"><p className="text-[10px] uppercase tracking-widest text-noc-muted">Challenge</p><p className="mt-1 text-sm text-noc-text">Complete the missing lines for: <b>{challenge.title}</b></p></div><div className="min-h-[570px] rounded-lg border border-noc-border bg-[#0d1824] p-3"><div className="mb-3 grid grid-cols-[34px_1fr] text-[10px] text-noc-muted"><span>LINE</span><span>PARTIALLY WRITTEN CONGESTION ALGORITHM</span></div>{section.program.map((id,lineIndex)=>{const slot=slotByLine.get(lineIndex);const placed=slot&&slots[slot]?BLOCKS.find((block)=>block.id===slots[slot]):null;const block=BLOCKS.find((item)=>item.id===id)!;return <div key={lineIndex} className="grid grid-cols-[34px_1fr] items-center py-1"><span className="text-right font-mono text-[10px] text-noc-muted">{lineIndex+1}</span>{slot?<button onDragOver={(e)=>e.preventDefault()} onDrop={()=>{if(dragged)place(slot,dragged);setDragged(null)}} className={`ml-3 min-h-10 rounded border border-dashed px-3 py-2 text-left font-mono text-xs ${placed?STYLE[placed.kind]:'border-link-congested/60 bg-link-congested/5 text-link-congested'}`}>{placed?placed.code:'[ missing line ]'}</button>:<div className={`ml-3 rounded border border-transparent px-3 py-2 font-mono text-xs ${STYLE[block.kind]}`}>{block.code}</div>}</div>})}</div></main>
      <aside className="border-l border-noc-border bg-noc-surface/60 p-3"><CongestionSimulation section={sectionId} status={status}/><section className="mt-3 rounded border border-noc-border bg-noc-bg/60 p-3"><p className="text-xs font-bold text-noc-bright">Live Variables</p><div className="mt-2 grid grid-cols-2 gap-y-1 font-mono text-[10px] text-noc-muted"><span>cwnd</span><b className="text-noc-text">{sectionId==='cubic'?84:sectionId==='bbr'?64:24} MSS</b><span>ssthresh</span><b className="text-noc-text">16 MSS</b><span>RTT</span><b className="text-noc-text">80 ms</b><span>phase</span><b className="text-module-b">{section.title}</b></div></section><section className="mt-3 rounded border border-noc-border bg-noc-bg/60 p-3"><p className="text-xs font-bold text-noc-bright">Feedback</p>{status==='idle'&&<p className="mt-2 text-xs text-noc-muted">Fill the missing lines and run the simulation.</p>}{status==='wrong'&&<p className="mt-2 text-xs text-link-down">The selected blocks do not produce the required TCP behavior.</p>}{status==='partial'&&<p className="mt-2 text-xs text-link-congested">Partially correct—some lines are in the right positions.</p>}{status==='correct'&&<p className="mt-2 text-xs text-link-up">✓ Algorithm behaves correctly.</p>}</section>{hintCount>0&&<div className="mt-3 rounded border border-link-congested/40 bg-link-congested/10 p-3 text-xs text-noc-text">💡 {hintCount===1?challenge.hint:`Correct missing lines: ${Object.values(expected).map((id)=>BLOCKS.find((b)=>b.id===id)?.label).join(' → ')}`}</div>}<div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setHintCount((n)=>Math.min(2,n+1))} className="rounded border border-link-congested/50 px-3 py-2 text-xs text-link-congested">Hint {Math.min(2,hintCount+1)}/2</button><button onClick={run} className="rounded bg-link-up px-3 py-2 text-xs font-bold text-noc-bg">▶ Run Simulation</button></div><button onClick={()=>setSlots({})} className="mt-2 w-full rounded border border-noc-border px-3 py-2 text-xs text-noc-muted">Reset Blanks</button></aside></div>
    {complete&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-xl border border-link-up/50 bg-noc-surface p-6 text-center"><h3 className="text-xl font-bold text-noc-bright">Simulation passed!</h3><p className="mt-1 text-sm text-link-up">+{hintCount===0&&attempts===0?100:hintCount<2?75:50} XP</p><p className="mx-auto mt-3 max-w-lg text-xs text-noc-muted">{section.explanation}</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><button onClick={()=>reset((questionIndex+1)%section.variants.length)} className="rounded border border-link-packet/50 bg-link-packet/10 px-4 py-3 text-sm text-link-packet">Another Question</button>{sectionIndex<ORDER.length-1&&<button onClick={nextSection} className="rounded border border-link-congested/50 bg-link-congested/10 px-4 py-3 text-sm text-link-congested">Next Section</button>}<button onClick={()=>{onComplete(true,hintCount);navigate('/sandbox')}} className="rounded bg-link-up px-4 py-3 text-sm font-bold text-noc-bg">Back to Sandbox</button></div></div></div>}
  </div>
}

function CongestionSimulation({section,status}:{section:SectionId;status:string}){
  const curves:Record<SectionId,number[]>={fundamentals:[1,2,4,8,16,17,18,19,10,11],tahoe:[1,2,4,8,16,1,2,4,8,9],reno:[1,2,4,8,16,10,11,12,13,14],vegas:[4,5,6,7,7,8,8,8,9,9],bbr:[8,20,42,62,64,63,65,64,64,65],cubic:[4,12,28,50,72,84,60,64,75,92]};const values=curves[section];const points=values.map((value,index)=>`${20+index*27},${145-value*1.25}`).join(' ')
  return <section className="rounded border border-noc-border bg-noc-bg/60 p-3"><div className="flex justify-between"><p className="text-xs font-bold text-noc-bright">Simulation</p><span className={`text-[10px] ${status==='correct'?'text-link-up':'text-link-packet'}`}>{status==='correct'?'● PASS':'● READY'}</span></div><svg viewBox="0 0 290 170" className="mt-2 w-full" role="img" aria-label={`${section} congestion window simulation`}><line x1="20" y1="150" x2="280" y2="150" stroke="#30363d"/><line x1="20" y1="20" x2="20" y2="150" stroke="#30363d"/><polyline points={points} fill="none" stroke="#bc8cff" strokeWidth="3"/>{values.map((value,index)=><circle key={index} cx={20+index*27} cy={145-value*1.25} r="3" fill="#58a6ff"/>)}<text x="150" y="166" textAnchor="middle" fill="#6e7681" fontSize="9">RTT</text><text x="8" y="82" textAnchor="middle" fill="#6e7681" fontSize="9" transform="rotate(-90 8 82)">cwnd</text></svg><div className="mt-2 flex items-center justify-between text-[10px] text-noc-muted"><span>Sender → Bottleneck → Receiver</span><span className="text-link-up">ACKs ↩</span></div></section>
}
