import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import type { Level } from '@/types'

interface Props { level: Level; onComplete: (passed: boolean, hintsUsed: number) => void }
type Kind = 'structure'|'variable'|'operator'|'control'|'value'|'function'
interface Block { id:string; label:string; kind:Kind; indent?:number }
interface Challenge { title:string; goal:string; expected:string[]; available:string[]; input:string; output:string; hints:string[] }

const BLOCKS: Block[] = [
  {id:'fn-hello',label:'function Hello()',kind:'function'},{id:'fn-double',label:'function Double(x)',kind:'function'},{id:'fn-max',label:'function Largest(a, b)',kind:'function'},{id:'fn-factorial',label:'function Factorial(n)',kind:'function'},
  {id:'end',label:'}',kind:'structure'},{id:'declare-score',label:'number score',kind:'variable',indent:1},{id:'declare-result',label:'number result',kind:'variable',indent:1},{id:'assign-10',label:'score = 10',kind:'operator',indent:1},{id:'counter-inc',label:'counter = counter + 1',kind:'operator',indent:1},
  {id:'return-double',label:'return x * 2',kind:'control',indent:1},{id:'return-sum',label:'return a + b',kind:'control',indent:1},{id:'return-true',label:'return true',kind:'control',indent:2},{id:'return-false',label:'return false',kind:'control',indent:2},{id:'return-a',label:'return a',kind:'control',indent:2},{id:'return-b',label:'return b',kind:'control',indent:2},{id:'return-result',label:'return result',kind:'control',indent:1},
  {id:'if-positive',label:'if (x > 0) {',kind:'control',indent:1},{id:'if-adult',label:'if (age >= 18) {',kind:'control',indent:1},{id:'if-a-b',label:'if (a > b) {',kind:'control',indent:1},{id:'if-score',label:'if (score > 50 && lives > 0) {',kind:'control',indent:1},{id:'else',label:'else {',kind:'control',indent:1},{id:'close-if',label:'}',kind:'structure',indent:1},
  {id:'for-10',label:'for (i = 1; i <= 10; i++) {',kind:'control',indent:1},{id:'while-n',label:'while (n > 1) {',kind:'control',indent:1},{id:'foreach-array',label:'foreach (value in numbers) {',kind:'control',indent:1},{id:'print-i',label:'print(i)',kind:'function',indent:2},{id:'print-win',label:'print("Win")',kind:'function',indent:2},
  {id:'result-one',label:'result = 1',kind:'operator',indent:1},{id:'multiply-n',label:'result = result * n',kind:'operator',indent:2},{id:'dec-n',label:'n = n - 1',kind:'operator',indent:2},{id:'array-empty',label:'array values = []',kind:'variable',indent:1},{id:'array-push',label:'values.push(item)',kind:'function',indent:2},{id:'reverse-loop',label:'foreach item from end to start {',kind:'control',indent:1},
  {id:'object-player',label:'object player = {}',kind:'variable',indent:1},{id:'set-name',label:'player.name = "Nova"',kind:'operator',indent:1},{id:'set-points',label:'player.points = 100',kind:'operator',indent:1},{id:'return-player',label:'return player',kind:'control',indent:1},
  {id:'wrong-print',label:'print(x)',kind:'function',indent:1},{id:'wrong-return',label:'return',kind:'control',indent:1},{id:'wrong-zero',label:'score = 0',kind:'operator',indent:1},
]

const TOPICS: Record<string,Challenge> = {
  structure:{title:'Program Structure',goal:'Build an empty function called Hello.',expected:['fn-hello','end'],available:['fn-hello','end','wrong-return','wrong-print'],input:'—',output:'Function Hello created',hints:['A program begins with a function block.','The function needs a closing brace.','Use function Hello(), then }.']},
  variables:{title:'Variables',goal:'Create a variable named score and assign it 10.',expected:['declare-score','assign-10'],available:['declare-score','assign-10','wrong-zero','wrong-return'],input:'—',output:'score = 10',hints:['Declare before assigning.','Choose the value 10.','number score comes before score = 10.']},
  operators:{title:'Expressions',goal:'Create a function that returns a + b.',expected:['fn-max','return-sum','end'],available:['fn-max','return-sum','return-a','wrong-return','end'],input:'a=4, b=7',output:'11',hints:['Start with a function containing a and b.','Use the addition expression.','Return a + b between the function and closing brace.']},
  comparisons:{title:'Comparisons',goal:'Return true when age is at least 18; otherwise false.',expected:['if-adult','return-true','close-if','else','return-false','close-if'],available:['if-adult','if-positive','return-true','return-false','else','close-if'],input:'age = 21',output:'true',hints:['“At least” means greater than or equal.','Both branches need a return.','Use if age >= 18, then true, else false.']},
  if:{title:'If Statements',goal:'Return true if x is positive.',expected:['if-positive','return-true','close-if'],available:['if-positive','if-adult','return-true','return-false','close-if'],input:'x = 5',output:'true',hints:['Compare x with zero.','The return belongs inside the if.','Use if (x > 0), return true, then close.']},
  else:{title:'If / Else',goal:'Return the larger of a and b.',expected:['fn-max','if-a-b','return-a','close-if','else','return-b','close-if','end'],available:['fn-max','if-a-b','return-a','return-b','return-sum','else','close-if','end'],input:'a=9, b=4',output:'9',hints:['Compare a with b.','Return a in the first branch and b in else.','Wrap the if/else inside Largest(a,b).']},
  nested:{title:'Nested Logic',goal:'Return true only if score > 50 AND lives > 0.',expected:['if-score','return-true','close-if','else','return-false','close-if'],available:['if-score','if-positive','return-true','return-false','else','close-if'],input:'score=80, lives=2',output:'true',hints:['Both conditions must be true.','Use the && condition block.','Return true inside the combined if; false in else.']},
  loops:{title:'Loops',goal:'Print the numbers 1 through 10.',expected:['for-10','print-i','close-if'],available:['for-10','while-n','foreach-array','print-i','print-win','close-if'],input:'—',output:'1 2 3 4 5 6 7 8 9 10',hints:['The repetition count is known in advance.','Use a for loop.','Place print(i) inside for 1..10.']},
  functions:{title:'Functions',goal:'Build Double(x), returning x multiplied by 2.',expected:['fn-double','return-double','end'],available:['fn-double','fn-max','return-double','wrong-print','wrong-return','end'],input:'x = 6',output:'12',hints:['Choose the function with parameter x.','A function result uses return.','Double(x), return x * 2, then close.']},
  arrays:{title:'Arrays',goal:'Reverse an array into a new values array.',expected:['array-empty','reverse-loop','array-push','close-if','return-result'],available:['array-empty','reverse-loop','foreach-array','array-push','close-if','return-result','wrong-return'],input:'[1, 2, 3]',output:'[3, 2, 1]',hints:['Start with an empty output array.','Walk the input from end to start.','Push each item, then return the result.']},
  objects:{title:'Objects',goal:'Create a player object with name Nova and 100 points.',expected:['object-player','set-name','set-points','return-player'],available:['object-player','set-name','set-points','declare-score','wrong-zero','return-player'],input:'—',output:'{ name: "Nova", points: 100 }',hints:['Create the object before setting fields.','Set name and points separately.','Create player, set both properties, then return it.']},
  algorithms:{title:'Mini Algorithm',goal:'Calculate factorial using a loop.',expected:['fn-factorial','result-one','while-n','multiply-n','dec-n','close-if','return-result','end'],available:['fn-factorial','result-one','while-n','for-10','multiply-n','dec-n','close-if','return-result','wrong-return','end'],input:'n = 5',output:'120',hints:['Factorial starts with result = 1.','Multiply by n, then decrement n in a loop.','Return result after the while loop.']},
}

const KIND_STYLE:Record<Kind,string>={structure:'border-noc-muted bg-noc-border/30 text-noc-text',variable:'border-noc-text/40 bg-noc-text/5 text-noc-bright',operator:'border-link-congested/50 bg-link-congested/10 text-link-congested',control:'border-module-b/50 bg-module-b/10 text-module-b',value:'border-link-up/50 bg-link-up/10 text-link-up',function:'border-link-packet/50 bg-link-packet/10 text-link-packet'}

function endlessChallenge(seed:number):Challenge {
  const pool=[TOPICS.variables,TOPICS.if,TOPICS.functions,TOPICS.loops,TOPICS.objects,TOPICS.algorithms]
  const generated=pool[seed%pool.length]
  return {...generated,title:`Endless Practice · ${generated.title}`,goal:`Generated challenge: ${generated.goal}`}
}

export function CodingPracticeIDE({level,onComplete}:Props){
  const navigate=useNavigate(); const topic=String(level.setup.codingTopic??'structure'); const [seed,setSeed]=useState(0)
  const challenge=useMemo(()=>topic==='endless'?endlessChallenge(seed):TOPICS[topic]??TOPICS.structure,[topic,seed])
  const [workspace,setWorkspace]=useState<string[]>([]); const [dragged,setDragged]=useState<string|null>(null); const [hintCount,setHintCount]=useState(0); const [attempts,setAttempts]=useState(0); const [consoleState,setConsoleState]=useState<'idle'|'wrong'|'correct'>('idle'); const [complete,setComplete]=useState(false)
  function add(id:string){setWorkspace((items)=>[...items,id]);setConsoleState('idle')} function drop(){if(dragged)add(dragged);setDragged(null)}
  function reset(){setWorkspace([]);setHintCount(0);setAttempts(0);setConsoleState('idle');setComplete(false)}
  function run(){const ok=workspace.length===challenge.expected.length&&workspace.every((id,index)=>id===challenge.expected[index]);if(ok){setConsoleState('correct');setComplete(true)}else{setAttempts((n)=>n+1);setConsoleState('wrong')}}
  const stars=hintCount===0&&attempts===0?3:hintCount<=1?2:1
  return <div className="overflow-hidden rounded-xl border border-noc-border bg-[#0b1017]"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-noc-border bg-noc-surface px-4 py-3"><div><p className="text-sm font-bold text-noc-bright">CODING PRACTICE IDE</p><p className="text-[10px] text-noc-muted">{level.id} · Structure first, syntax second</p></div><p className="text-sm font-semibold text-module-b">{challenge.title}</p><span className="text-link-congested">{'★'.repeat(stars)}{'☆'.repeat(3-stars)}</span></header><div className="border-b border-noc-border bg-noc-bg/60 px-4 py-3"><p className="text-[10px] uppercase tracking-widest text-noc-muted">Objective</p><p className="mt-1 text-sm text-noc-text">{challenge.goal}</p></div>
    <div className="grid min-h-[650px] lg:grid-cols-[220px_1fr_270px]"><aside className="border-r border-noc-border bg-noc-surface/60 p-3"><p className="mb-3 text-xs font-bold text-noc-bright">Available Blocks</p><div className="flex flex-col gap-1.5">{challenge.available.map((id)=>{const block=BLOCKS.find((item)=>item.id===id)!;return <button key={id} draggable onDragStart={()=>setDragged(id)} onClick={()=>add(id)} className={`rounded border px-2 py-2 text-left font-mono text-[10px] ${KIND_STYLE[block.kind]}`}>{block.label}</button>})}</div>{hintCount>0&&<div className="mt-4 rounded border border-link-congested/40 bg-link-congested/10 p-3 text-xs text-noc-text">💡 {challenge.hints[Math.min(hintCount-1,2)]}</div>}<button onClick={()=>setHintCount((n)=>Math.min(3,n+1))} className="mt-3 w-full rounded border border-link-congested/50 px-3 py-2 text-xs text-link-congested">Hint {Math.min(3,hintCount+1)}/3</button></aside>
      <main className="p-4"><div onDragOver={(e)=>e.preventDefault()} onDrop={drop} className="min-h-[570px] rounded-lg border border-noc-border bg-[#0d141e] p-3"><div className="mb-3 grid grid-cols-[34px_1fr] text-[10px] text-noc-muted"><span>LINE</span><span>FAKE IDE · blocks auto-indent</span></div>{workspace.length===0&&<div className="grid h-72 place-items-center rounded border border-dashed border-noc-border text-xs text-noc-muted">Drag or click blocks to build the program</div>}{workspace.map((id,index)=>{const block=BLOCKS.find((item)=>item.id===id)!;return <div key={`${id}-${index}`} className="grid grid-cols-[34px_1fr_auto] items-center gap-2 py-1"><span className="text-right font-mono text-[10px] text-noc-muted">{index+1}</span><div className={`rounded border px-3 py-2 font-mono text-xs ${KIND_STYLE[block.kind]}`} style={{marginLeft:`${(block.indent??0)*20}px`}}>{block.label}</div><button onClick={()=>setWorkspace((items)=>items.filter((_,i)=>i!==index))} className="text-link-down">×</button></div>})}</div></main>
      <aside className="border-l border-noc-border bg-noc-surface/60 p-3"><section className="rounded-lg border border-noc-border bg-black/30 p-3 font-mono text-xs"><p className="text-noc-muted">FAKE CONSOLE</p><p className="mt-3 text-link-packet">Program Running...</p><p className="mt-3 text-noc-muted">Input</p><p className="text-noc-text">{challenge.input}</p><p className="mt-3 text-noc-muted">Output</p><p className={consoleState==='correct'?'text-link-up':consoleState==='wrong'?'text-link-down':'text-noc-muted'}>{consoleState==='correct'?challenge.output:consoleState==='wrong'?'Program structure does not match expected AST.':'—'}</p>{consoleState==='correct'&&<p className="mt-3 text-link-up">✓ Correct</p>}</section><button onClick={run} className="mt-4 w-full rounded-lg bg-link-up px-4 py-3 text-sm font-bold text-noc-bg">▶ Run Program</button><button onClick={()=>setWorkspace([])} className="mt-2 w-full rounded border border-noc-border px-3 py-2 text-xs text-noc-muted">Clear</button></aside></div>
    {complete&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-xl rounded-xl border border-link-up/50 bg-noc-surface p-6 text-center"><h3 className="text-xl font-bold text-noc-bright">Perfect Run</h3><p className="mt-2 text-link-up">+{stars===3?20:stars===2?12:8} XP · {'★'.repeat(stars)}</p><p className="mt-3 text-sm text-noc-muted">{stars===3?'Syntax Master · No hints used':'Program complete · Keep practicing'}</p><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={()=>{if(topic==='endless')setSeed((n)=>n+1);reset()}} className="rounded-lg border border-link-packet/50 bg-link-packet/10 px-4 py-3 text-sm text-link-packet">Another Challenge</button><button onClick={()=>{onComplete(true,hintCount);navigate('/sandbox')}} className="rounded-lg bg-link-up px-4 py-3 text-sm font-bold text-noc-bg">Back to Sandbox</button></div></div></div>}
  </div>
}
